### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by rawwry** [iganeshk/adwireguard-dark#2]
hey there :)

i've been trying to get your container to work for ages :D
I have a Raspberry Pi4 here and have absolutely no idea why the whole thing won't boot.

this is my portiner stack. some details 'bout my lansettings:

router is 192.168.178.1 and raspi is 192.168.178.10.

that would be really great if you could help me here briefly

`version: "3.8"

services:
  adwireguard:
    container_name: adwireguard
    #image: ghcr.io/iganeshk/adwireguard-dark:latest
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '22890:3000'       # Default Address AdGuardHome WebUI
      - '22853:853'        # DNS-TLS
      - '22820:51820/udp'  # wiregaurd port
      - '22843:51821/tcp'  # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=cloud.rawwr.org
      - PASSWORD=xxxxx
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.11.x
      - WG_DEFAULT_DNS=10.10.10.2
      - WG_MTU=1420
    volumes:
        # adguard-home volume
      - '/opt/containers/adwireguard/work:/opt/adwireguard/work'
      - '/opt/containers/adwireguard/config:/opt/adwireguard/conf'
        # wg-easy volume
      - '/opt/containers/adwireguard/wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      vpn_net:
        ipv4_address: 10.10.10.2

networks:
  vpn_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24`

**Comment by gyaneesh** [comment]
Hey, looks like* there was an issue with node-18 image for wg-easy in the dockerfile.

I built a temporary image to address this, Can you try pulling this `ghcr.io/iganeshk/adwireguard-easy:arm64` image in the compose and give it a shot? I don't posses any arm64 device at the moment.

**Comment by gyaneesh** [comment]
I emulated arm64 on my workstation and  I was able to test that image out!
```
root@zenbian:~# docker run -it -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static \
--platform linux/arm64 \
--rm -t ghcr.io/iganeshk/adwireguard-easy:arm64 uname -m
aarch64
```
Keep me posted!

**Comment by gyaneesh** [comment]
Quick update, the latest images on dockerhub should fix this issue.

**Comment by gyaneesh** [comment]
marking this as closed due to inactivity
