### ISSUE TITLE
DNS resolving has broken on latest release

### ISSUE THREAD

**Issue by uncapped1599** [iganeshk/adwireguard-dark#8]
Hey,

Been using your image for quite a few months with no issues. This morning I updated to latest and now all DNS resolution seems to have broken. 

I confirmed this by removing your container and running just plain WG-Easy image and all works fine. When I run your image all pings slow to a crawl from host machine and any clients connected to adwireguard can no longer resolve any URLs.

Not sure what exactly is going on, I tried rebuilding my resolv.conf and re-applying NetworkManager.conf with no luck.

Running on Ubuntu 22.04.2 LTS with Docker.

**Comment by gyaneesh** [comment]
https://github.com/iganeshk/adwireguard-dark/issues/7#issuecomment-1806265165

about to update the readme!
